### ISSUE TITLE
BCUI库文档需要！！！

### ISSUE THREAD

**Issue by Riceneeder** [Stapxs/Border-Card-UI#1]
border card ui for web 的风格比较符合胃口，我去项目介绍的网页看了，应该还不完整，想要更加完整的文档😁

**Comment by Stapxs** [comment]
BCUI 项目暂时属于 Stapxs-Web-API 下，此项目暂缓更新（我在忙着写毕设）
这个设计风格其实没啥严谨的控件库 ……
现有的也是我用着顺手写的整理出来的
等我之后有空我会慢慢整理出来（小声

**Comment by Riceneeder** [comment]
> BCUI 项目暂时属于 Stapxs-Web-API 下，此项目暂缓更新（我在忙着写毕设）
> 这个设计风格其实没啥严谨的控件库 ……
> 现有的也是我用着顺手写的整理出来的
> 等我之后有空我会慢慢整理出来（小声
> 

好的好的，毕业要紧，到时候独立出来单独一个仓库后请踢我一下，我来⭐

**Comment by wuxian425** [comment]
> > BCUI 项目暂时属于 Stapxs-Web-API 下，此项目暂缓更新（我在忙着写毕设）
> > 这个设计风格其实没啥严谨的控件库 ……
> > 现有的也是我用着顺手写的整理出来的
> > 等我之后有空我会慢慢整理出来（小声
> 
> 好的好的，毕业要紧，到时候独立出来单独一个仓库后请踢我一下，我来star

踢（雾

**Comment by Stapxs** [comment]
> > > BCUI 项目暂时属于 Stapxs-Web-API 下，此项目暂缓更新（我在忙着写毕设）
> > > 这个设计风格其实没啥严谨的控件库 ……
> > > 现有的也是我用着顺手写的整理出来的
> > > 等我之后有空我会慢慢整理出来（小声
> > 
> > 
> > 好的好的，毕业要紧，到时候独立出来单独一个仓库后请踢我一下，我来star
> 
> 踢（雾

你住 github 上的吗（x

**Comment by wuxian425** [comment]
> > > > BCUI 项目暂时属于 Stapxs-Web-API 下，此项目暂缓更新（我在忙着写毕设）
> > > > 这个设计风格其实没啥严谨的控件库 ……
> > > > 现有的也是我用着顺手写的整理出来的
> > > > 等我之后有空我会慢慢整理出来（小声
> > > 
> > > 
> > > 好的好的，毕业要紧，到时候独立出来单独一个仓库后请踢我一下，我来star
> > 
> > 
> > 踢（雾
> 
> 你住 github 上的吗（x

没有（确信
寄生虫（x

**Comment by Stapxs** [comment]
把文档摸完了 ……
https://stapxs.github.io/Border-Card-UI/

不过全线换成了 vue 组件 XD
纯 js 版本也保留着不过不打算维护了 ……
